server.error.include-message: always

iTunes:
  rootUrl: https://itunes.apple.com/
  cache:
    ttlSeconds: 3600
    maximumSize: 100

springdoc:
  packagesToScan: lt.tazkazz.mrqtr.web.v1
  apiDocs:
    path: /api-docs